import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from src.config import Config
from src.etl.ingestion import DataIngestion
from src.etl.validation import DataValidator
from src.etl.transformation import DataTransformer

# Page Configuration
st.set_page_config(
    page_title="Stock Market Analytics Platform",
    page_icon="📈",
    layout="wide"
)

# Title and Intro
st.title("📈 Stock Market ETL & Analytics Platform")
st.markdown("""
This dashboard demonstrates the **Analytics Engineering** capabilities of the platform.
It fetches real-time data, validates it, and calculates advanced time-series metrics.
""")

# Sidebar for controls
st.sidebar.header("Configuration")
selected_tickers = st.sidebar.multiselect(
    "Select Tickers",
    options=Config.TICKERS,
    default=["AAPL", "TSLA"]
)
period = st.sidebar.selectbox("Period", ["1mo", "3mo", "6mo", "1y", "2y", "5y"], index=3)

if not selected_tickers:
    st.warning("Please select at least one ticker.")
else:
    # --- ETL Phase 1: Ingestion ---
    with st.spinner('Running ETL Pipeline (Ingestion -> Validation -> Transformation)...'):
        ingestor = DataIngestion(selected_tickers)
        raw_df = ingestor.fetch_data(period=period)
        
        # --- ETL Phase 2: Validation ---
        if raw_df.empty:
            st.error("No data fetched.")
        else:
            clean_df, quality_report = DataValidator.check_data_quality(raw_df)
            
            # --- ETL Phase 3: Transformation ---
            enriched_df = DataTransformer.add_technical_indicators(clean_df)
            
            st.success("ETL Pipeline completed successfully!")

            # --- Dashboard Layout ---
            
            # 1. Key Metrics Row
            st.subheader("📊 Key Market Metrics (Latest)")
            latest_date = enriched_df['date'].max()
            st.caption(f"Data as of: {latest_date.date()}")
            
            cols = st.columns(len(selected_tickers))
            for idx, ticker in enumerate(selected_tickers):
                ticker_data = enriched_df[enriched_df['ticker'] == ticker].iloc[-1]
                prev_data = enriched_df[enriched_df['ticker'] == ticker].iloc[-2]
                
                price_change = ticker_data['close'] - prev_data['close']
                pct_change = (price_change / prev_data['close']) * 100
                
                with cols[idx]:
                    st.metric(
                        label=ticker,
                        value=f"${ticker_data['close']:.2f}",
                        delta=f"{price_change:.2f} ({pct_change:.2f}%)"
                    )

            # 2. Charts Section
            tab1, tab2, tab3 = st.tabs(["💰 Price Trends", "📉 Volatility Analysis", "🛠 Data Quality"])
            
            with tab1:
                st.subheader("Close Price History")
                fig_price = px.line(
                    enriched_df, 
                    x='date', 
                    y='close', 
                    color='ticker',
                    title="Daily Closing Price",
                    template="plotly_dark"
                )
                st.plotly_chart(fig_price, use_container_width=True)
                
            with tab2:
                st.subheader("Volatility (Risk) Analysis")
                st.markdown("Rolling 20-day annualized volatility. Higher peaks indicate higher risk regimes.")
                fig_vol = px.line(
                    enriched_df,
                    x='date',
                    y='volatility_20d',
                    color='ticker',
                    title="20-Day Rolling Volatility (Annualized)",
                    template="plotly_dark"
                )
                st.plotly_chart(fig_vol, use_container_width=True)
                
            with tab3:
                st.subheader("Data Quality Report")
                st.json(quality_report)
                
                st.markdown("### Sample Data (Post-Validation)")
                st.dataframe(enriched_df.tail(10))

# Footer
st.markdown("---")
st.markdown("Generated by **Stock Market ETL & Analytics Platform** | [View Source Info](#)")
